Mongo utils#1679
bosch-io/hono pull request #3
Opened 2020-02-24 15:25 UTC by ko-j

- add mongodb utils
- update pom.xml files

2020-02-24 15:46 UTC, kaniyan commented
@ko-j Can you please rebase it, there are some conflicting files.

2020-02-25 12:41 UTC, kaniyan requested changes

2020-02-25 12:41 UTC, kaniyan commented on services/device-registry/device-registry-mongodb/pom.xml
> +                                            <port>8443</port>junitparams
_junitparams_ here? Also please build and check.

2020-02-25 12:41 UTC, kaniyan commented on services/device-registry/device-registry-mongodb/pom.xml
> +        <relativePath>..</relativePath>
@ko-j This relative path is not needed here. The build fails.

2020-02-25 12:50 UTC, ko-j commented on services/device-registry/device-registry-mongodb/pom.xml
> +                                            <port>8443</port>junitparams
resolved

2020-02-25 12:50 UTC, ko-j commented on services/device-registry/device-registry-mongodb/pom.xml
> +        <relativePath>..</relativePath>
resolved

2020-02-26 10:12 UTC, kaniyan commented on services/device-registry/device-registry-mongodb/pom.xml
> +            <scope>test</scope>
These 2 junit dependencies are not being used and can be removed.

2020-02-26 11:05 UTC, kaniyan requested changes

2020-02-26 11:05 UTC, kaniyan commented on services/device-registry/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDBCallExecutor.java
> +     * @param vertx         acting vertx context
How about `@param vertx The Vert.x instance to use.`

2020-02-26 11:05 UTC, kaniyan commented on services/device-registry/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDBCallExecutor.java
> +     * @param mongoDbConfig mongodb config properties
How about `The mongodb configuration properties to use.`?

2020-02-26 11:25 UTC, merged